### ISSUE TITLE
Implement graph with pointers as verts

### ISSUE THREAD

**Issue by va9abond** [va9abond/codebase-cpp#2]
#### Motivation
It is convenient to use pointers as vertices because
- it's presenting strong connection between verts and edges
- (i think) convenient way to add/remove verts in graph
- (Edge contraction)[https://en.wikipedia.org/wiki/Edge_contraction]

#### Tasks
- [x] `Graph_base_::m_Verts<vert*>`
- [x] Dtor for `Graph_base_`
- [x] (?) implement `edge` as separated struct with Ctor and Dtor
- [x] `weighter_graph::m_Edges<vert*, vert*>`
- [x] Dtor `weighted_graph`

**Comment by va9abond** [comment]
Commit `6641f46` close this issue
